### ISSUE TITLE
typos on Python page

### ISSUE THREAD

**Issue by natespain** [masondesu/cool-new-ironyard-site#238]
![screen shot 2015-01-07 at 1 59 12 pm](https://cloud.githubusercontent.com/assets/1322902/5651651/44c71540-9677-11e4-9e1f-fc8da1bd15f2.png)
![screen shot 2015-01-07 at 1 59 54 pm](https://cloud.githubusercontent.com/assets/1322902/5651652/44cae31e-9677-11e4-8684-75fdf1ccee1c.png)

**Comment by joetamburro** [comment]
fixed
