### ISSUE TITLE
Typo in Kids Classes section of Locations page

### ISSUE THREAD

**Issue by ericdodds** [masondesu/cool-new-ironyard-site#247]
Let's check all of the other ones to make sure the error wasn't replicated through copy/paste. 

![screen_shot_2015-01-14_at_8_34_13_am](https://cloud.githubusercontent.com/assets/2762024/5745130/77254444-9bf4-11e4-85f8-1d153e64adf7.jpg)

**Comment by joetamburro** [comment]
Twas just this one. Check
